---
# PMM Demo Workload Generator
- hosts: postgresqlservers

  vars:
    percona_workload_generator_repo: 'https://github.com/michaelcoburn/pmm-demo.git'
    percona_workload_generator_directory: /opt/percona/oltp

  tasks:
    - name: install Percona repo on red hat family hosts
      yum:
        name={{ percona_mysql_repo }}
        name=http://www.percona.com/downloads/percona-release/redhat/0.1-4/percona-release-0.1-4.noarch.rpm
        state=present
    - name: Install sysbench for PMM Demo Workload generator
      yum: name=sysbench state=present
    - name: Ensure directory is present for PMM Demo Workload generator
      file: 
        path:  "{{ percona_workload_generator_directory }}"
        mode: 0755
        state: directory
    - name: Install git
      yum: name=git state=present
    - name: Checkout PMM Demo Workload generator from github.com/michaelcoburn/pmm-demo
      git:
        repo: "{{ percona_workload_generator_repo }}"
        dest: "{{ percona_workload_generator_directory }}"
        version: postgresql_support

    - name: Start PMM Demo Workload generator
      shell: "{{ percona_workload_generator_directory }}/install {{ ansible_hostname }}"
    - name: Advertise that Workload was re-generated
      shell: "pmm-admin annotate 'Deployed latest PMM Demo Workload Generator from github.com/michaelcoburn/pmm-demo' --tags 'deploy'"
