#!/bin/sh

set -o xtrace

DBNAME=innodb
ENGINE=innodb
TABLE_SIZE=10000000
TEST=/usr/share/sysbench/tests/include/oltp_legacy/oltp.lua
SOCKET=${1:-/var/run/mysqld/mysqld.sock}
RATE=1
THREADS=1
DURATION=1800

if [ -S "$SOCKET" ]; then
    CONNECTION="--socket=$SOCKET"
    SB_CONNECTION="--mysql-socket=$SOCKET"
else
    CONNECTION="--host=$SOCKET"
    SB_CONNECTION="--mysql-host=$SOCKET"
fi

mysql \
    $CONNECTION \
    --user=sbtest \
    --password=sbtest \
    -e "CREATE DATABASE IF NOT EXISTS $DBNAME"
sysbench \
    $SB_CONNECTION \
    --db-driver=mysql \
    --mysql-user=sbtest \
    --mysql-password=sbtest \
    --mysql-db=$DBNAME \
    --mysql-table-engine=$ENGINE \
    --oltp-table-size=$TABLE_SIZE \
    $TEST \
    prepare

while true; do
    for rand_type in uniform gaussian special pareto; do
        pmm-admin annotate "Distribution: $rand_type" --tags "$rand_type"
        sysbench \
            $SB_CONNECTION \
            --rate=$RATE \
            --threads=$THREADS \
            --report-interval=10 \
            --time=$DURATION \
            --events=0 \
            --rand-type=$rand_type \
            --db-driver=mysql \
            --mysql-user=sbtest \
            --mysql-password=sbtest \
            --mysql-db=$DBNAME \
            --mysql-table-engine=$ENGINE \
            --oltp-reconnect \
            --oltp-table-size=$TABLE_SIZE \
            $TEST \
            run
        sleep 60
        done
done
