---
- hosts: localhost
  connection: local
  gather_facts: no

  vars:
    droplets:
    # Percona Server for MySQL
    #- { name: ps55, group: "mysqlservers" }
    #- { name: ps56, group: "mysqlservers" }
    #- { name: ps57, group: "mysqlservers", size: 's-4vcpu-8gb' }
    #- { name: ps57slave, group: "mysqlservers" }
    #- { name: ps57tokudb, group: "mysqlservers" }
    #- { name: ps57myrocks, group: "mysqlservers" }
    # PMM Server
    #- { name: pmmserver, group: "pmmservers", size: 's-4vcpu-8gb' }
    # PXC
    #- { name: pxc57-1, group: "mysqlservers", image_id: 'ubuntu-14-04-x64' }
    #- { name: pxc57-2, group: "mysqlservers", image_id: 'ubuntu-14-04-x64' }
    #- { name: pxc57-3, group: "mysqlservers", image_id: 'ubuntu-14-04-x64' }
    # ProxySQL
    #- { name: proxysql, group:  "proxysqlservers" }
    # MariaDB
    #- { name: mariadb103, group: "mysqlservers" }
    # MySQL Community
    #- { name: mysql57, group: "mysqlservers" }
    #- { name: mysql80, group: "mysqlservers" }
    # Run the PostgreSQL playbook
    - { name: pg10, group: "postgresqlservers" }
    # Run the Percona Server for MongoDB 3.6 playbook
    # Run the MongoDB 3.6 playbook

  tasks:
    - name: Provision DigitalOcean droplets.
      digital_ocean:
        state: "{{ item.state | default('present') }}"
        command: droplet
        name: "{{ item.name }}"
        private_networking: yes
        size_id: "{{ item.size | default('s-3vcpu-1gb') }}"
        image_id: "{{ item.image | default('centos-7-x64') }}"
        region_id: "{{ item.region | default('sfo2') }}"
        ssh_key_ids: "{{ item.ssh_key | default('11186103') }}"
        unique_name: yes
        wait: no
      register: created_droplets
      with_items: "{{ droplets }}"

    - name: Add DigitalOcean hosts to inventory groups.
      add_host:
        name: "{{ item.1.droplet.ip_address }}"
        groups: "do,{{ droplets[item.0].group }},{{ item.1.droplet.name }}"
      when: item.1.droplet is defined
      with_indexed_items: "{{ created_droplets.results }}"

    - pause:
        prompt: Wait for DO to finish buidling the targets
        seconds: 120
