---
# PXC Playbook
- hosts:
      - pxc57-1
      - pxc57-2
      - pxc57-3

  vars:
    percona_master_node: pxc57-1
    mysql_root_password: percona
    wsrep_cluster_name: pxc57
    wsrep_cluster_hosts:
      - pxc57-1
      - pxc57-2
      - pxc57-3

  roles:
      - tkuhlman.percona
